name: Release RubyGem
on:
  push:
    tags:
      - '*'
jobs:
  release:
    name: Release RubyGem
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Release
        run: bash ./scripts/release-gem.sh
        env:
          RUBYGEMS_API_TOKEN: ${{ secrets.RUBYGEMS_API_TOKEN }}
